/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.api;

import com.relationalai.client.ApiException;
import com.relationalai.client.model.QueryActionResult;
import org.junit.Test;

import static com.relationalai.test.ExtendedTestCase.*;

/**
 * API tests for DefaultApi
 */
public class IntegrationTestsCommons {

    /**
     * Issues a transaction to be executed
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public static void transactionPostTest(DelveClient api) throws ApiException {
        Connection conn = api.getConn();
        assertTrue( api.create_database(conn, true) );
        assertThrows( RuntimeException.class, () -> api.create_database(conn, false) );


        assertNotNull( api.install_source(conn, "name", "name", "def foo = 1") );
        QueryActionResult queryRes = api.query(conn, "name", "name", "def bar = 2", "bar");
        assertNotNull( queryRes );
        System.out.println(queryRes);
    }


}
