/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.api;

import com.relationalai.client.ApiException;
import com.relationalai.client.builder.Query;
import com.relationalai.client.model.QueryActionResult;
import org.junit.Test;

import java.io.IOException;
import java.util.Arrays;

import static com.relationalai.test.ExtendedTestCase.*;

/**
 * API tests for DefaultApi
 */
public class IntegrationTestsCommons {

    /**
     * Issues a transaction to be executed
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public static void transactionPostLocalTest(LocalConnection api) throws ApiException, IOException {
        assertTrue( api.createDatabase(true) );
        assertThrows( RuntimeException.class, () -> api.createDatabase(false) );

        Query query = Query.builder()
                .name("name")
                .path("name")
                .value("def bar = 2")
                .outputs(Arrays.asList("bar"))
                .build();

        assertNotNull( api.installSource("name", "name", "def foo = 1") );
        QueryActionResult queryRes = api.query(query);
        assertNotNull( queryRes );
        System.out.println(queryRes);
    }

    @Test
    public static void transactionPostCloudTest(CloudConnection api) throws ApiException, IOException {
        assertTrue( api.createDatabase(true) );
        assertThrows( RuntimeException.class, () -> api.createDatabase(false) );
        Query query = Query.builder()
                .name("name")
                .path("name")
                .value("def bar = 2")
                .outputs(Arrays.asList("bar"))
                .build();

        assertNotNull( api.installSource("name", "name", "def foo = 1") );
        QueryActionResult queryRes = api.query(query);
        assertNotNull( queryRes );
        System.out.println(queryRes);
    }


}
