/*
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.cloudclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.cloudclient.model.ComputeCreditsInfo;
import com.relationalai.cloudclient.model.StorageCreditsInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * GetAccountCreditsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetAccountCreditsResponse {
  public static final String SERIALIZED_NAME_START_PERIOD = "start_period";
  @SerializedName(SERIALIZED_NAME_START_PERIOD)
  private OffsetDateTime startPeriod;

  public static final String SERIALIZED_NAME_END_PERIOD = "end_period";
  @SerializedName(SERIALIZED_NAME_END_PERIOD)
  private OffsetDateTime endPeriod;

  public static final String SERIALIZED_NAME_COMPUTE = "compute";
  @SerializedName(SERIALIZED_NAME_COMPUTE)
  private ComputeCreditsInfo compute;

  public static final String SERIALIZED_NAME_STORAGE = "storage";
  @SerializedName(SERIALIZED_NAME_STORAGE)
  private StorageCreditsInfo storage;


  public GetAccountCreditsResponse startPeriod(OffsetDateTime startPeriod) {
    
    this.startPeriod = startPeriod;
    return this;
  }

   /**
   * Get startPeriod
   * @return startPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartPeriod() {
    return startPeriod;
  }


  public void setStartPeriod(OffsetDateTime startPeriod) {
    this.startPeriod = startPeriod;
  }


  public GetAccountCreditsResponse endPeriod(OffsetDateTime endPeriod) {
    
    this.endPeriod = endPeriod;
    return this;
  }

   /**
   * Get endPeriod
   * @return endPeriod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getEndPeriod() {
    return endPeriod;
  }


  public void setEndPeriod(OffsetDateTime endPeriod) {
    this.endPeriod = endPeriod;
  }


  public GetAccountCreditsResponse compute(ComputeCreditsInfo compute) {
    
    this.compute = compute;
    return this;
  }

   /**
   * Get compute
   * @return compute
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ComputeCreditsInfo getCompute() {
    return compute;
  }


  public void setCompute(ComputeCreditsInfo compute) {
    this.compute = compute;
  }


  public GetAccountCreditsResponse storage(StorageCreditsInfo storage) {
    
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StorageCreditsInfo getStorage() {
    return storage;
  }


  public void setStorage(StorageCreditsInfo storage) {
    this.storage = storage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAccountCreditsResponse getAccountCreditsResponse = (GetAccountCreditsResponse) o;
    return Objects.equals(this.startPeriod, getAccountCreditsResponse.startPeriod) &&
        Objects.equals(this.endPeriod, getAccountCreditsResponse.endPeriod) &&
        Objects.equals(this.compute, getAccountCreditsResponse.compute) &&
        Objects.equals(this.storage, getAccountCreditsResponse.storage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPeriod, endPeriod, compute, storage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAccountCreditsResponse {\n");
    sb.append("    startPeriod: ").append(toIndentedString(startPeriod)).append("\n");
    sb.append("    endPeriod: ").append(toIndentedString(endPeriod)).append("\n");
    sb.append("    compute: ").append(toIndentedString(compute)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

