/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CardinalityActionResult;
import org.openapitools.client.model.CollectProblemsActionResult;
import org.openapitools.client.model.ImportActionResult;
import org.openapitools.client.model.InstallActionResult;
import org.openapitools.client.model.ListEdbActionResult;
import org.openapitools.client.model.ListSourceActionResult;
import org.openapitools.client.model.LoadDataActionResult;
import org.openapitools.client.model.ModifyWorkspaceActionResult;
import org.openapitools.client.model.ParseActionResult;
import org.openapitools.client.model.QueryActionResult;
import org.openapitools.client.model.SetOptionsActionResult;
import org.openapitools.client.model.UpdateActionResult;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ActionResult
 */
public class ActionResultTest {
    private final ActionResult model = new ActionResult();

    /**
     * Model tests for ActionResult
     */
    @Test
    public void testActionResult() {
        // TODO: test ActionResult
    }

    /**
     * Test the property 'objtp'
     */
    @Test
    public void objtpTest() {
        // TODO: test objtp
    }

}
