/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CardinalityAction;
import org.openapitools.client.model.CollectProblemsAction;
import org.openapitools.client.model.ImportAction;
import org.openapitools.client.model.InstallAction;
import org.openapitools.client.model.ListEdbAction;
import org.openapitools.client.model.ListSourceAction;
import org.openapitools.client.model.LoadDataAction;
import org.openapitools.client.model.ModifyWorkspaceAction;
import org.openapitools.client.model.ParseAction;
import org.openapitools.client.model.QueryAction;
import org.openapitools.client.model.SetOptionsAction;
import org.openapitools.client.model.UpdateAction;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Action
 */
public class ActionTest {
    private final Action model = new Action();

    /**
     * Model tests for Action
     */
    @Test
    public void testAction() {
        // TODO: test Action
    }

    /**
     * Test the property 'objtp'
     */
    @Test
    public void objtpTest() {
        // TODO: test objtp
    }

}
