/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CollectProblemsActionAllOf
 */
public class CollectProblemsActionAllOfTest {
    private final CollectProblemsActionAllOf model = new CollectProblemsActionAllOf();

    /**
     * Model tests for CollectProblemsActionAllOf
     */
    @Test
    public void testCollectProblemsActionAllOf() {
        // TODO: test CollectProblemsActionAllOf
    }

    /**
     * Test the property 'dummy'
     */
    @Test
    public void dummyTest() {
        // TODO: test dummy
    }

}
