/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.client.model.RelKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModifyWorkspaceActionResultAllOf
 */
public class ModifyWorkspaceActionResultAllOfTest {
    private final ModifyWorkspaceActionResultAllOf model = new ModifyWorkspaceActionResultAllOf();

    /**
     * Model tests for ModifyWorkspaceActionResultAllOf
     */
    @Test
    public void testModifyWorkspaceActionResultAllOf() {
        // TODO: test ModifyWorkspaceActionResultAllOf
    }

    /**
     * Test the property 'deleteEdbResult'
     */
    @Test
    public void deleteEdbResultTest() {
        // TODO: test deleteEdbResult
    }

}
