/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetOptionsActionAllOf
 */
public class SetOptionsActionAllOfTest {
    private final SetOptionsActionAllOf model = new SetOptionsActionAllOf();

    /**
     * Model tests for SetOptionsActionAllOf
     */
    @Test
    public void testSetOptionsActionAllOf() {
        // TODO: test SetOptionsActionAllOf
    }

    /**
     * Test the property 'abortOnError'
     */
    @Test
    public void abortOnErrorTest() {
        // TODO: test abortOnError
    }

    /**
     * Test the property 'debug'
     */
    @Test
    public void debugTest() {
        // TODO: test debug
    }

    /**
     * Test the property 'debugTrace'
     */
    @Test
    public void debugTraceTest() {
        // TODO: test debugTrace
    }

    /**
     * Test the property 'silent'
     */
    @Test
    public void silentTest() {
        // TODO: test silent
    }

}
