/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.client.model.PairAnyValueAnyValue;
import com.relationalai.client.model.RelKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateActionAllOf
 */
public class UpdateActionAllOfTest {
    private final UpdateActionAllOf model = new UpdateActionAllOf();

    /**
     * Model tests for UpdateActionAllOf
     */
    @Test
    public void testUpdateActionAllOf() {
        // TODO: test UpdateActionAllOf
    }

    /**
     * Test the property 'delta'
     */
    @Test
    public void deltaTest() {
        // TODO: test delta
    }

    /**
     * Test the property 'rel'
     */
    @Test
    public void relTest() {
        // TODO: test rel
    }

    /**
     * Test the property 'updates'
     */
    @Test
    public void updatesTest() {
        // TODO: test updates
    }

}
