/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.relational.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.relational.client.model.Action;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LabeledAction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LabeledAction {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name = "";

  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private Action action;

  /**
   * Gets or Sets objtp
   */
  @JsonAdapter(ObjtpEnum.Adapter.class)
  public enum ObjtpEnum {
    LABELEDACTION("LabeledAction");

    private String value;

    ObjtpEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjtpEnum fromValue(String value) {
      for (ObjtpEnum b : ObjtpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ObjtpEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjtpEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjtpEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ObjtpEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_OBJTP = "objtp";
  @SerializedName(SERIALIZED_NAME_OBJTP)
  private ObjtpEnum objtp = ObjtpEnum.LABELEDACTION;


  public LabeledAction name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public LabeledAction action(Action action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(required = true, value = "")

  public Action getAction() {
    return action;
  }


  public void setAction(Action action) {
    this.action = action;
  }


  public LabeledAction objtp(ObjtpEnum objtp) {
    
    this.objtp = objtp;
    return this;
  }

   /**
   * Get objtp
   * @return objtp
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjtpEnum getObjtp() {
    return objtp;
  }


  public void setObjtp(ObjtpEnum objtp) {
    this.objtp = objtp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LabeledAction labeledAction = (LabeledAction) o;
    return Objects.equals(this.name, labeledAction.name) &&
        Objects.equals(this.action, labeledAction.action) &&
        Objects.equals(this.objtp, labeledAction.objtp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, action, objtp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LabeledAction {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    objtp: ").append(toIndentedString(objtp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

