/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.relational.client.model;

import java.util.Objects;
import java.util.Arrays;
import ai.relational.client.model.AbstractProblem;
import ai.relational.client.model.LabeledActionResult;
import ai.relational.client.model.RelDict;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TransactionResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TransactionResult {
  public static final String SERIALIZED_NAME_OUTPUT = "output";
  @SerializedName(SERIALIZED_NAME_OUTPUT)
  private RelDict output;

  public static final String SERIALIZED_NAME_PROBLEMS = "problems";
  @SerializedName(SERIALIZED_NAME_PROBLEMS)
  private List<AbstractProblem> problems = null;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<LabeledActionResult> actions = null;

  public static final String SERIALIZED_NAME_ABORTED = "aborted";
  @SerializedName(SERIALIZED_NAME_ABORTED)
  private Boolean aborted = false;

  /**
   * Gets or Sets objtp
   */
  @JsonAdapter(ObjtpEnum.Adapter.class)
  public enum ObjtpEnum {
    TRANSACTIONRESULT("TransactionResult");

    private String value;

    ObjtpEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjtpEnum fromValue(String value) {
      for (ObjtpEnum b : ObjtpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ObjtpEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjtpEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjtpEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ObjtpEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_OBJTP = "objtp";
  @SerializedName(SERIALIZED_NAME_OBJTP)
  private ObjtpEnum objtp = ObjtpEnum.TRANSACTIONRESULT;


  public TransactionResult output(RelDict output) {
    
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RelDict getOutput() {
    return output;
  }


  public void setOutput(RelDict output) {
    this.output = output;
  }


  public TransactionResult problems(List<AbstractProblem> problems) {
    
    this.problems = problems;
    return this;
  }

  public TransactionResult addProblemsItem(AbstractProblem problemsItem) {
    if (this.problems == null) {
      this.problems = new ArrayList<AbstractProblem>();
    }
    this.problems.add(problemsItem);
    return this;
  }

   /**
   * Get problems
   * @return problems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AbstractProblem> getProblems() {
    return problems;
  }


  public void setProblems(List<AbstractProblem> problems) {
    this.problems = problems;
  }


  public TransactionResult actions(List<LabeledActionResult> actions) {
    
    this.actions = actions;
    return this;
  }

  public TransactionResult addActionsItem(LabeledActionResult actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<LabeledActionResult>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<LabeledActionResult> getActions() {
    return actions;
  }


  public void setActions(List<LabeledActionResult> actions) {
    this.actions = actions;
  }


  public TransactionResult aborted(Boolean aborted) {
    
    this.aborted = aborted;
    return this;
  }

   /**
   * Get aborted
   * @return aborted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAborted() {
    return aborted;
  }


  public void setAborted(Boolean aborted) {
    this.aborted = aborted;
  }


  public TransactionResult objtp(ObjtpEnum objtp) {
    
    this.objtp = objtp;
    return this;
  }

   /**
   * Get objtp
   * @return objtp
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjtpEnum getObjtp() {
    return objtp;
  }


  public void setObjtp(ObjtpEnum objtp) {
    this.objtp = objtp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionResult transactionResult = (TransactionResult) o;
    return Objects.equals(this.output, transactionResult.output) &&
        Objects.equals(this.problems, transactionResult.problems) &&
        Objects.equals(this.actions, transactionResult.actions) &&
        Objects.equals(this.aborted, transactionResult.aborted) &&
        Objects.equals(this.objtp, transactionResult.objtp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(output, problems, actions, aborted, objtp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionResult {\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    problems: ").append(toIndentedString(problems)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    aborted: ").append(toIndentedString(aborted)).append("\n");
    sb.append("    objtp: ").append(toIndentedString(objtp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

