/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.client.model.ArityMismatchError;
import com.relationalai.client.model.ClientProblem;
import com.relationalai.client.model.ComparisonChainError;
import com.relationalai.client.model.ExceptionProblem;
import com.relationalai.client.model.FrontProblem;
import com.relationalai.client.model.InlineInconsistent;
import com.relationalai.client.model.IntegrityConstraintProblem;
import com.relationalai.client.model.IntegrityConstraintViolation;
import com.relationalai.client.model.OutputProblem;
import com.relationalai.client.model.PersistProblem;
import com.relationalai.client.model.StorageProblem;
import com.relationalai.client.model.SyntaxError;
import com.relationalai.client.model.UndefinedError;
import com.relationalai.client.model.WorkspaceLoadProblem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AbstractProblem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AbstractProblem {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  protected String type = "";

  public AbstractProblem() {
    this.type = this.getClass().getSimpleName();
  }

  public AbstractProblem type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractProblem abstractProblem = (AbstractProblem) o;
    return Objects.equals(this.type, abstractProblem.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractProblem {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

