/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.client.model.LinkedList;
import com.relationalai.client.model.SyntaxNode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConsAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConsAllOf {
  public static final String SERIALIZED_NAME_HEAD = "head";
  @SerializedName(SERIALIZED_NAME_HEAD)
  private SyntaxNode head;

  public static final String SERIALIZED_NAME_TAIL = "tail";
  @SerializedName(SERIALIZED_NAME_TAIL)
  private LinkedList tail;


  public ConsAllOf head(SyntaxNode head) {
    
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  @ApiModelProperty(required = true, value = "")

  public SyntaxNode getHead() {
    return head;
  }


  public void setHead(SyntaxNode head) {
    this.head = head;
  }


  public ConsAllOf tail(LinkedList tail) {
    
    this.tail = tail;
    return this;
  }

   /**
   * Get tail
   * @return tail
  **/
  @ApiModelProperty(required = true, value = "")

  public LinkedList getTail() {
    return tail;
  }


  public void setTail(LinkedList tail) {
    this.tail = tail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsAllOf consAllOf = (ConsAllOf) o;
    return Objects.equals(this.head, consAllOf.head) &&
        Objects.equals(this.tail, consAllOf.tail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(head, tail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsAllOf {\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    tail: ").append(toIndentedString(tail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

