/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.relational.client.model;

import ai.relational.client.model.ClientProblem;
import ai.relational.client.model.ExceptionProblem;
import ai.relational.client.model.IntegrityConstraintProblem;
import ai.relational.client.model.IntegrityConstraintViolation;
import ai.relational.client.model.OutputProblem;
import ai.relational.client.model.PersistProblem;
import ai.relational.client.model.SyntaxError;
import ai.relational.client.model.UndefinedError;
import ai.relational.client.model.WorkspaceLoadProblem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AbstractProblem
 */
public class AbstractProblemTest {
    private final AbstractProblem model = new AbstractProblem();

    /**
     * Model tests for AbstractProblem
     */
    @Test
    public void testAbstractProblem() {
        // TODO: test AbstractProblem
    }

    /**
     * Test the property 'objtp'
     */
    @Test
    public void objtpTest() {
        // TODO: test objtp
    }

}
