/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.relational.client.model;

import ai.relational.client.model.Action;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModifyWorkspaceAction
 */
public class ModifyWorkspaceActionTest {
    private final ModifyWorkspaceAction model = new ModifyWorkspaceAction();

    /**
     * Model tests for ModifyWorkspaceAction
     */
    @Test
    public void testModifyWorkspaceAction() {
        // TODO: test ModifyWorkspaceAction
    }

    /**
     * Test the property 'objtp'
     */
    @Test
    public void objtpTest() {
        // TODO: test objtp
    }

}
