/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AnyValue;
import org.openapitools.client.model.Area;

/**
 * Range
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-03T02:10:24.995237-07:00[America/Vancouver]")
public class Range {
  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private AnyValue input;

  public static final String SERIALIZED_NAME_AREA = "area";
  @SerializedName(SERIALIZED_NAME_AREA)
  private Area area;

  public static final String SERIALIZED_NAME_START_BYTE = "start_byte";
  @SerializedName(SERIALIZED_NAME_START_BYTE)
  private Integer startByte = null;

  public static final String SERIALIZED_NAME_END_BYTE = "end_byte";
  @SerializedName(SERIALIZED_NAME_END_BYTE)
  private Integer endByte = null;

  /**
   * Gets or Sets objtp
   */
  @JsonAdapter(ObjtpEnum.Adapter.class)
  public enum ObjtpEnum {
    RANGE("Range");

    private String value;

    ObjtpEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjtpEnum fromValue(String value) {
      for (ObjtpEnum b : ObjtpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ObjtpEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjtpEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjtpEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ObjtpEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_OBJTP = "objtp";
  @SerializedName(SERIALIZED_NAME_OBJTP)
  private ObjtpEnum objtp = ObjtpEnum.RANGE;


  public Range input(AnyValue input) {
    
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AnyValue getInput() {
    return input;
  }


  public void setInput(AnyValue input) {
    this.input = input;
  }


  public Range area(Area area) {
    
    this.area = area;
    return this;
  }

   /**
   * Get area
   * @return area
  **/
  @ApiModelProperty(required = true, value = "")

  public Area getArea() {
    return area;
  }


  public void setArea(Area area) {
    this.area = area;
  }


  public Range startByte(Integer startByte) {
    
    this.startByte = startByte;
    return this;
  }

   /**
   * Get startByte
   * @return startByte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getStartByte() {
    return startByte;
  }


  public void setStartByte(Integer startByte) {
    this.startByte = startByte;
  }


  public Range endByte(Integer endByte) {
    
    this.endByte = endByte;
    return this;
  }

   /**
   * Get endByte
   * @return endByte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getEndByte() {
    return endByte;
  }


  public void setEndByte(Integer endByte) {
    this.endByte = endByte;
  }


  public Range objtp(ObjtpEnum objtp) {
    
    this.objtp = objtp;
    return this;
  }

   /**
   * Get objtp
   * @return objtp
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjtpEnum getObjtp() {
    return objtp;
  }


  public void setObjtp(ObjtpEnum objtp) {
    this.objtp = objtp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Range range = (Range) o;
    return Objects.equals(this.input, range.input) &&
        Objects.equals(this.area, range.area) &&
        Objects.equals(this.startByte, range.startByte) &&
        Objects.equals(this.endByte, range.endByte) &&
        Objects.equals(this.objtp, range.objtp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, area, startByte, endByte, objtp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Range {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    area: ").append(toIndentedString(area)).append("\n");
    sb.append("    startByte: ").append(toIndentedString(startByte)).append("\n");
    sb.append("    endByte: ").append(toIndentedString(endByte)).append("\n");
    sb.append("    objtp: ").append(toIndentedString(objtp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

