/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LabeledAction;

/**
 * Transaction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Transaction {
  public static final String SERIALIZED_NAME_DBNAME = "dbname";
  @SerializedName(SERIALIZED_NAME_DBNAME)
  private String dbname = "";

  /**
   * Gets or Sets mode
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    OPEN("OPEN"),
    
    CREATE("CREATE"),
    
    CREATE_OVERWRITE("CREATE_OVERWRITE"),
    
    OPEN_OR_CREATE("OPEN_OR_CREATE");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private ModeEnum mode = ModeEnum.OPEN;

  public static final String SERIALIZED_NAME_READONLY = "readonly";
  @SerializedName(SERIALIZED_NAME_READONLY)
  private Boolean readonly = false;

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  private List<LabeledAction> actions = null;

  public static final String SERIALIZED_NAME_ABORT = "abort";
  @SerializedName(SERIALIZED_NAME_ABORT)
  private Boolean abort = false;

  /**
   * Gets or Sets objtp
   */
  @JsonAdapter(ObjtpEnum.Adapter.class)
  public enum ObjtpEnum {
    TRANSACTION("Transaction");

    private String value;

    ObjtpEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjtpEnum fromValue(String value) {
      for (ObjtpEnum b : ObjtpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ObjtpEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjtpEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjtpEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ObjtpEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_OBJTP = "objtp";
  @SerializedName(SERIALIZED_NAME_OBJTP)
  private ObjtpEnum objtp = ObjtpEnum.TRANSACTION;


  public Transaction dbname(String dbname) {
    
    this.dbname = dbname;
    return this;
  }

   /**
   * Get dbname
   * @return dbname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDbname() {
    return dbname;
  }


  public void setDbname(String dbname) {
    this.dbname = dbname;
  }


  public Transaction mode(ModeEnum mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(required = true, value = "")

  public ModeEnum getMode() {
    return mode;
  }


  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }


  public Transaction readonly(Boolean readonly) {
    
    this.readonly = readonly;
    return this;
  }

   /**
   * Get readonly
   * @return readonly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReadonly() {
    return readonly;
  }


  public void setReadonly(Boolean readonly) {
    this.readonly = readonly;
  }


  public Transaction actions(List<LabeledAction> actions) {
    
    this.actions = actions;
    return this;
  }

  public Transaction addActionsItem(LabeledAction actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<LabeledAction>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<LabeledAction> getActions() {
    return actions;
  }


  public void setActions(List<LabeledAction> actions) {
    this.actions = actions;
  }


  public Transaction abort(Boolean abort) {
    
    this.abort = abort;
    return this;
  }

   /**
   * Get abort
   * @return abort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAbort() {
    return abort;
  }


  public void setAbort(Boolean abort) {
    this.abort = abort;
  }


  public Transaction objtp(ObjtpEnum objtp) {
    
    this.objtp = objtp;
    return this;
  }

   /**
   * Get objtp
   * @return objtp
  **/
  @ApiModelProperty(required = true, value = "")

  public ObjtpEnum getObjtp() {
    return objtp;
  }


  public void setObjtp(ObjtpEnum objtp) {
    this.objtp = objtp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.dbname, transaction.dbname) &&
        Objects.equals(this.mode, transaction.mode) &&
        Objects.equals(this.readonly, transaction.readonly) &&
        Objects.equals(this.actions, transaction.actions) &&
        Objects.equals(this.abort, transaction.abort) &&
        Objects.equals(this.objtp, transaction.objtp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dbname, mode, readonly, actions, abort, objtp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    dbname: ").append(toIndentedString(dbname)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    readonly: ").append(toIndentedString(readonly)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    abort: ").append(toIndentedString(abort)).append("\n");
    sb.append("    objtp: ").append(toIndentedString(objtp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

