/*
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AbstractProblem;
import org.openapitools.client.model.Range;

/**
 * UndefinedError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-08-03T02:10:24.995237-07:00[America/Vancouver]")
public class UndefinedError extends AbstractProblem {
  public static final String SERIALIZED_NAME_RANGE = "range";
  @SerializedName(SERIALIZED_NAME_RANGE)
  private Range range;

  public static final String SERIALIZED_NAME_VAR = "var";
  @SerializedName(SERIALIZED_NAME_VAR)
  private String var = "";

  public UndefinedError() {
    this.objtp = this.getClass().getSimpleName();
  }

  public UndefinedError range(Range range) {
    
    this.range = range;
    return this;
  }

   /**
   * Get range
   * @return range
  **/
  @ApiModelProperty(required = true, value = "")

  public Range getRange() {
    return range;
  }


  public void setRange(Range range) {
    this.range = range;
  }


  public UndefinedError var(String var) {
    
    this.var = var;
    return this;
  }

   /**
   * Get var
   * @return var
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVar() {
    return var;
  }


  public void setVar(String var) {
    this.var = var;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UndefinedError undefinedError = (UndefinedError) o;
    return Objects.equals(this.range, undefinedError.range) &&
        Objects.equals(this.var, undefinedError.var) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(range, var, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UndefinedError {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    var: ").append(toIndentedString(var)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

