/*
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.0.13
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.cloudclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ComputeData
 */
public class ComputeDataTest {
    private final ComputeData model = new ComputeData();

    /**
     * Model tests for ComputeData
     */
    @Test
    public void testComputeData() {
        // TODO: test ComputeData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'getEtag'
     */
    @Test
    public void getEtagTest() {
        // TODO: test getEtag
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'computeId'
     */
    @Test
    public void computeIdTest() {
        // TODO: test computeId
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'computeName'
     */
    @Test
    public void computeNameTest() {
        // TODO: test computeName
    }

    /**
     * Test the property 'computeSize'
     */
    @Test
    public void computeSizeTest() {
        // TODO: test computeSize
    }

    /**
     * Test the property 'computeRegion'
     */
    @Test
    public void computeRegionTest() {
        // TODO: test computeRegion
    }

    /**
     * Test the property 'infrastructure'
     */
    @Test
    public void infrastructureTest() {
        // TODO: test infrastructure
    }

    /**
     * Test the property 'computeState'
     */
    @Test
    public void computeStateTest() {
        // TODO: test computeState
    }

    /**
     * Test the property 'requestedOn'
     */
    @Test
    public void requestedOnTest() {
        // TODO: test requestedOn
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'deletedOn'
     */
    @Test
    public void deletedOnTest() {
        // TODO: test deletedOn
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
