/*
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.cloudclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.relationalai.cloudclient.model.ComputeCreditsInfo;
import com.relationalai.cloudclient.model.StorageCreditsInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetAccountCreditsResponse
 */
public class GetAccountCreditsResponseTest {
    private final GetAccountCreditsResponse model = new GetAccountCreditsResponse();

    /**
     * Model tests for GetAccountCreditsResponse
     */
    @Test
    public void testGetAccountCreditsResponse() {
        // TODO: test GetAccountCreditsResponse
    }

    /**
     * Test the property 'startPeriod'
     */
    @Test
    public void startPeriodTest() {
        // TODO: test startPeriod
    }

    /**
     * Test the property 'endPeriod'
     */
    @Test
    public void endPeriodTest() {
        // TODO: test endPeriod
    }

    /**
     * Test the property 'compute'
     */
    @Test
    public void computeTest() {
        // TODO: test compute
    }

    /**
     * Test the property 'storage'
     */
    @Test
    public void storageTest() {
        // TODO: test storage
    }

}
