/*
 * RAI Cloud SDK
 * This is a Client SDK for RAI Cloud
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.relationalai.cloudclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateDatabaseRequestProtocol
 */
public class UpdateDatabaseRequestProtocolTest {
    private final UpdateDatabaseRequestProtocol model = new UpdateDatabaseRequestProtocol();

    /**
     * Model tests for UpdateDatabaseRequestProtocol
     */
    @Test
    public void testUpdateDatabaseRequestProtocol() {
        // TODO: test UpdateDatabaseRequestProtocol
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'defaultComputeName'
     */
    @Test
    public void defaultComputeNameTest() {
        // TODO: test defaultComputeName
    }

    /**
     * Test the property 'removeDefaultCompute'
     */
    @Test
    public void removeDefaultComputeTest() {
        // TODO: test removeDefaultCompute
    }

    /**
     * Test the property 'dryrun'
     */
    @Test
    public void dryrunTest() {
        // TODO: test dryrun
    }

}
